### ISSUE TITLE
Broken link in the readme

### ISSUE THREAD

**Issue by umarcor** [DavePearce/StronglyConnectedComponents#1]
> A nice blog article of the algorithm can be found [here](http://www.timl.id.au/?p=327).

The link above (at timl.id.au) seems to be broken. Is it available elsewhere?

/cc @timleslie

**Comment by timleslie** [comment]
That link should be updated to http://timl.id.au/SCC/

**Comment by umarcor** [comment]
Thanks!

**Comment by DavePearce** [comment]
Merged in now --- thanks @umarcor and @timleslie !!!!
